[theme]
primaryColor = "#2457D6"
backgroundColor = "#F4F7FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#111B33"
font = "sans-serif"

[browser]
gatherUsageStats = false

[server]
headless = true
maxUploadSize = 25
